version: '3.8'

services:
  # Main service that exposes metrics
  solana-exporter:
    image: python:3.9-slim
    container_name: solana-exporter
    ports:
      - "8080:8080"
    volumes:
      - ./monitoring/sample-metrics.py:/app/sample-metrics.py
    working_dir: /app
    command: python sample-metrics.py
    networks:
      - monitoring-net

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: sprint-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus-fixed.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: sprint-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  monitoring-net:
    name: monitoring-net
