app = "bitcoin-sprint-fastapi"
primary_region = "iad"

[build]
  dockerfile = "fly/fastapi/Dockerfile"

[env]
  PORT = "8080"
  ENVIRONMENT = "production"
  LOG_LEVEL = "info"
  GIN_MODE = "release"
  SPRINTD_PORT = "9090"
  FASTAPI_PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [services.concurrency]
    type = "requests"
    soft_limit = 1000
    hard_limit = 2000

[metrics]
  port = 8080
  path = "/metrics"

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "10s"
    method = "GET"
    path = "/health"

  [checks.backend]
    port = 8080
    type = "http"
    interval = "60s"
    timeout = "15s"
    method = "GET"
    path = "/api/v1/backend/status"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[mounts]
  source = "bitcoin_sprint_data"
  destination = "/app/data"
