# Bitcoin Sprint - Consolidated Prometheus Configuration
# Supports all tiers with automatic service discovery

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alert rules for monitoring
rule_files:
  - /etc/prometheus/alerts.yml

# Scrape configuration for all Bitcoin Sprint services
scrape_configs:
  
  # === PROMETHEUS SELF-MONITORING ===
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # === BITCOIN SPRINT API TIERS ===
  # FREE Tier
  - job_name: 'bitcoin-sprint-free'
    static_configs:
      - targets: ['bitcoin-sprint:8080', 'localhost:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      tier: ['free']

  # BUSINESS Tier  
  - job_name: 'bitcoin-sprint-business'
    static_configs:
      - targets: ['bitcoin-sprint:8082', 'localhost:8082']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      tier: ['business']

  # ENTERPRISE Tier
  - job_name: 'bitcoin-sprint-enterprise'
    static_configs:
      - targets: ['bitcoin-sprint:9000', 'localhost:9000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      tier: ['enterprise']

  # === WEB DASHBOARD METRICS ===
  # Next.js Web Dashboard (all tiers)
  - job_name: 'bitcoin-sprint-web'
    static_configs:
      - targets: ['bitcoin-sprint-web:3000', 'bitcoin-sprint-web:3001', 'bitcoin-sprint-web:3002']
    scrape_interval: 15s
    metrics_path: '/api/prometheus'

  # === BLOCKCHAIN EXPORTERS ===
  # Bitcoin Core Exporter
  - job_name: 'bitcoin-exporter'
    static_configs:
      - targets: ['bitcoin-exporter:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Solana Validator/Exporter
  - job_name: 'solana-exporter'
    static_configs:
      - targets: ['solana-exporter:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # === INFRASTRUCTURE MONITORING ===
  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['sprint-grafana:3000', 'grafana:3003']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # Redis (if enabled)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL (if enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # === FASTAPI GATEWAY ===
  # FastAPI Gateway Service
  - job_name: 'fastapi-gateway'
    static_configs:
      - targets: ['fastapi-gateway:8000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # === RUST SERVICES ===
  # Rust Entropy Service
  - job_name: 'rust-entropy'
    static_configs:
      - targets: ['rust-entropy:3030']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # === NETWORK DISCOVERY ===
  # Dynamic service discovery for development
  - job_name: 'local-services'
    static_configs:
      - targets: ['127.0.0.1:8080', '127.0.0.1:8082', '127.0.0.1:9000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

# Global labels for all metrics
external_labels:
  cluster: 'bitcoin-sprint'
  environment: 'production'
  version: '2.1.0'
