# Prometheus configuration for Bitcoin Sprint Multi-Chain Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sprint-monitor'
    env: 'production'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Bitcoin Sprint Core API
  - job_name: 'bitcoin-sprint-api'
    static_configs:
      - targets: ['bitcoin-sprint:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Bitcoin Sprint API (main service)
  - job_name: 'bitcoin-sprint-main'
    static_configs:
      - targets: ['bitcoin-sprint:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Bitcoin Core monitoring
  - job_name: 'bitcoin-core'
    static_configs:
      - targets: ['bitcoin-core:8332']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Ethereum Geth monitoring
  - job_name: 'ethereum-geth'
    static_configs:
      - targets: ['geth:6060']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 30s

  # Solana validator monitoring
  - job_name: 'solana-validator'
    static_configs:
      - targets: ['solana-exporter:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Solana RPC monitoring
  - job_name: 'solana-rpc'
    static_configs:
      - targets: ['solana-validator:8899']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Cosmos Hub monitoring
  - job_name: 'cosmos-hub'
    static_configs:
      - targets: ['cosmos-hub:26660']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Polkadot node monitoring
  - job_name: 'polkadot-node'
    static_configs:
      - targets: ['polkadot-node:9615']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # RabbitMQ monitoring
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Elasticsearch monitoring
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # System monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200
