# Bitcoin Sprint - Storage Verification Service Configuration
# This file contains configuration options for the enhanced storage verification service

[server]
# Server configuration
host = "0.0.0.0"
port = 8080
workers = 8
shutdown_timeout_seconds = 30

[logging]
# Logging configuration
level = "info"  # error, warn, info, debug, trace
format = "json"  # json, compact, pretty

[connection]
# HTTP connection configuration
max_connections = 100
connect_timeout_seconds = 10
request_timeout_seconds = 30
pool_idle_timeout_seconds = 90
max_idle_connections_per_host = 10
keep_alive_seconds = 60
user_agent = "Bitcoin-Sprint-Storage-Verifier/1.0"

[circuit_breaker]
# Circuit breaker configuration
failure_threshold = 5
recovery_timeout_seconds = 60
success_threshold = 3

[rate_limiting]
# Rate limiting configuration
max_requests_per_window = 10
rate_window_seconds = 60
cleanup_interval_seconds = 60

[retry]
# Retry configuration
max_retries = 3
initial_backoff_ms = 100
max_backoff_ms = 10000
backoff_multiplier = 2.0

[storage_providers]
# Supported storage providers
ipfs = true
arweave = true
filecoin = true

[verification]
# Verification configuration
max_file_size_bytes = 1073741824  # 1GB
min_file_size_bytes = 1024         # 1KB
sample_count_max = 10
challenge_expiry_seconds = 300     # 5 minutes

[monitoring]
# Monitoring configuration
metrics_enabled = true
health_check_interval_seconds = 30
connection_health_enabled = true

[security]
# Security configuration
request_size_limit_bytes = 1048576  # 1MB
rate_limit_enabled = true
input_validation_enabled = true
cors_enabled = false

# CORS configuration (if enabled)
[cors]
allowed_origins = ["http://localhost:3000", "https://app.bitcoin-sprint.com"]
allowed_methods = ["GET", "POST", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-API-Key"]
allow_credentials = true
max_age_seconds = 3600

[external_services]
# External service endpoints
entropy_endpoint = "https://entropy.example.com"
contract_address = "0x0000000000000000000000000000000000000000"

[features]
# Feature flags
circuit_breaker_enabled = true
retry_logic_enabled = true
connection_pooling_enabled = true
health_monitoring_enabled = true
structured_logging_enabled = true
