app = "bitcoin-sprint-grafana"
primary_region = "iad"

[build]
  dockerfile = "fly/grafana/Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [services.concurrency]
    type = "connections"
    soft_limit = 1000
    hard_limit = 2000

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "10s"
    method = "GET"
    path = "/api/health"
