apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9091
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sprint_db
    user: sprint
    secureJsonData:
      password: sprint
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      
  - name: JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://host.docker.internal:8080
    isDefault: false
    editable: true
    jsonData:
      cache: "300"
      tlsSkipVerify: true
    secureJsonData:
      # API key will be configured in Grafana UI for security
      # Authorization header will be set to: Bearer <api_key>
