apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9091
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sprint_db
    user: sprint
    secureJsonData:
      password: sprint
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 8
      
  - name: Bitcoin Sprint Direct
    type: prometheus
    access: proxy
    url: http://localhost:8082
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      queryTimeout: 60s
      timeInterval: 15s
