apiVersion: 1

datasources:
  - name: Prometheus-Solana
    type: prometheus
    access: proxy
    url: http://host.docker.internal:19099
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
    secureJsonData: {}
