name: Windows CGO Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Toolchain summary
        shell: pwsh
        run: |
          go version
          rustc --version
          cargo --version
          where clang-cl.exe || write-host 'clang-cl not found'
          where gcc.exe || write-host 'gcc not found'

      - name: Run Windows helper (CGO + build + tests)
        shell: pwsh
        run: |
          .\tools\dev-win.ps1
